import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

import { useSession, signIn, signOut } from "next-auth/react"

export default function Home() {
  const { data: session, status } = useSession()
  const loading = status === "loading"
  if (loading) {
		return <div>loading...</div>;
	};
  console.log("home session: ",session)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Cheppy
        </h1>

        <div className={styles.grid}>
        {
            session ?
            <a className={styles.card} onClick={() => signOut()}>
              <h2>Logout &rarr;</h2>
            </a>
            :
            <a className={styles.card} onClick={() => signIn()}>
              <h2>Login &rarr;</h2>
            </a>
            
        }
          {/* <Link href="/login">
            <a className={styles.card}>
              <h2>Login &rarr;</h2>
            </a>
          </Link> */}
          <Link href="/signup">
            <a className={styles.card}>
              <h2>Sign up &rarr;</h2>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
